### ISSUE TITLE
Prenotazione ombrellone

### ISSUE THREAD

**Issue by danieleavolio** [cristiandrami/university_notes#1]
Ciao quanto viene quello in prima fila?

**Comment by maikuvit** [comment]
> Ciao quanto viene quello in prima fila?

Ciao, dovrebbe essere sui 12 al giorno ma aspetta conferma dalla struttura per essere certo.

Buona giornata 😊

**Comment by danieleavolio** [comment]
> > Ciao quanto viene quello in prima fila?
> 
> Ciao, dovrebbe essere sui 12 al giorno ma aspetta conferma dalla struttura per essere certo.
> 
> Buona giornata 😊

Ok, grazie. Chiudo.

**Comment by danieleavolio** [comment]
Vado a Corigliano
